@startuml
left to right direction
skinparam packageStyle rectangle
actor Groupement
actor Adhérent
database Database
database Mailer

Groupement -> Adhérent

rectangle "Gestion des clés" {
    Adhérent -- (Historique d'achats de clés)
    Adhérent -- (Historique des transactions)
    Adhérent -- (Achat de clés)
    Adhérent -- (Don de clés)
    Adhérent -- (Rétrocession de clés)
    (Historique d'achat de clés) -- Database
    (Historique des transactions) -- Database
    (Achat de clés) -- Mailer
    (Don de clés) -- Mailer
    (Achat de clés) -- Database
    (Détail d'une transaction) .> (Historique des transactions) : extends
}
@enduml