security:
    encoders:
        App\Entity\User\User:
            algorithm: auto
        App\Entity\Administrator:
            algorithm: auto
    providers:
        user_provider:
            entity:
                class: App\Entity\User\User
                property: username
        admin_provider:
            entity:
                class: App\Entity\Administrator
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: true
            lazy: true
            pattern: ^/admin
            provider: admin_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31536000
                path: /
            guard:
                authenticators:
                    - App\Security\Guard\AdminAuthenticator
            logout:
                path: admin_security_logout
        main:
            anonymous: true
            lazy: true
            provider: user_provider
            switch_user: { role: ROLE_MANAGER }
            user_checker: App\Security\UserChecker\UserChecker
            guard:
                authenticators:
                    - App\Security\Guard\WebAuthenticator
            logout:
                path: security_logout
                target: security_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31536000
                path: /
    role_hierarchy:
        ROLE_MANAGER: [ROLE_CLIENT_ACCESS, ROLE_CLIENT_ACCESS_CREATE, ROLE_CLIENT_COMPANY, ROLE_SHOP, ROLE_KEY_PURCHASE, ROLE_KEY_TRANSFER, ROLE_EMPLOYEE, ROLE_ADDRESS]
        ROLE_SALES_PERSON: [ROLE_CLIENT_ACCESS, ROLE_SHOP, ROLE_EMPLOYEE, ROLE_ADDRESS]
        ROLE_COLLABORATOR: [ROLE_SHOP, ROLE_EMPLOYEE, ROLE_ADDRESS]
        ROLE_CUSTOMER: [ROLE_SHOP, ROLE_ADDRESS]
    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/contact, roles: PUBLIC_ACCESS }
        - { path: ^/mot-de-passe-oublie$, roles: PUBLIC_ACCESS }
        - { path: ^/reinitialisation-mot-de-passe, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
