framework:
    workflows:
        purchase:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Key\Purchase
            initial_marking: pending
            places:
                - pending
                - refused
                - canceled
                - accepted
            transitions:
                cancel:
                    from: pending
                    to: canceled
                refuse:
                    from: pending
                    to: refused
                accept:
                    from: pending
                    to: accepted
        order:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\Order\Order
            initial_marking: cart
            places:
                - cart
                - pending
            transitions:
                valid_cart:
                    from: cart
                    to: pending
