name: Continuous Deployment
on: [push]
jobs:
  ci:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - name: Deploy from develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.SSH_DIRECTORY }}/${BRANCH_NAME}
            git checkout -B ${BRANCH_NAME}
            git pull origin ${BRANCH_NAME}
            make deploy
