name: Prepare Deployment
on:
  pull_request:
    types: [opened]
jobs:
  ci:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Prepare deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.SSH_DIRECTORY }}
            BRANCH=${{ env.GITHUB_REF_SLUG }} make install
            BRANCH=${{ env.GITHUB_REF_SLUG }} DATABASE_USER=root DATABASE_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }} make --directory=${{ env.GITHUB_REF_SLUG }} install
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            Installation d'un nouvel environnement
            [https://key-privilege-${{ env.GITHUB_REF_SLUG }}.thomas-boileau.dev](https://key-privilege-${{ env.GITHUB_REF_SLUG }}.thomas-boileau.dev)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'